import icon from './icon.png'
import shoppingBag from './shopping-bag.jpg'
import userImages from './user.jpg'
import  elle from './elle.png'
import byrdie from './byrdie.png'
import popSugar from './pop-sugar.png'
import shape from './shape.png'
import winner from './winner.png'
import fastCompany from './fast-company.png'
import cream from './cream.jpg'	
import losion from './losion.png'
import creamEverist from './cream-everist.jpg'
import creams  from './Creams.jpg'
import evCream from './ev-creams.png'
import hairWash from './hairWash.jpg'
import loading from './loading.gif'
import basket from './basket.png'
export const IMAGES={
icon,loading,basket,shoppingBag, hairWash,evCream,userImages,elle,byrdie,popSugar,shape,winner,fastCompany,cream,losion,creamEverist,creams,
}